spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:3306/captchadb
    username: root
#    password: Password1!
    password: Orion@123
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
